---
- hosts: network_devices
  gather_facts: no
##################################################################################  
  tasks:
##################################################################################
    - name: Fetch Running Configuration
      ios_command:
        commands:
          - show running-config
      register: config

    - set_fact:
        is_ios: "{{ os == 'IOS/IOS XE' }}"

    - name: Define Backup Directory Path
      set_fact:
        backup_dir: "/tmp/{{ playbook_dir | basename }}/{{ ansible_network_os }}/{{ ansible_hostname }}"
      when: is_ios
        
    - name: Create Backup Directory If It Doesn't Exist
      file:
        path: "{{ backup_dir }}"
        state: directory
        recurse: yes
      when: is_ios

    - name: Save Running Configuration Locally
      copy:
        content: "{{ config.stdout[0] }}"
        dest: "{{ backup_dir }}/{{ inventory_hostname }}.cfg"
      when: is_ios
        
  ##################################################################################
    - name: Git Add
      git:
        repo: "/tmp/{{ playbook_dir | basename }}"
        add: "*"
      when: is_ios

    - name: Git Commit
      git:
        repo: "/tmp/{{ playbook_dir | basename }}"
        msg: "Backed up {{ ansible_hostname }} on {{ lookup('pipe', 'date \"+%Y-%m-%d %H:%M:%S\"') }}"
        commit: yes
      when: is_ios

    - name: Git Push
      git:
        repo: "/tmp/{{ playbook_dir | basename }}"
        push: yes
      when: is_ios

    - name: Check if OS is IOS/IOS XE
      debug:
        msg: "The OS is IOS/IOS XE"
      when: is_ios

    - name: Display the backup directory
      debug:
        msg: "Backup directory is {{ backup_dir }}"
      when: is_ios
